In this notebook, we will learn about numpy library.

In [1]:
import numpy as np

Create numpy array

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
zeros = np.zeros(6)

In [5]:
ones = np.ones(5)

In [9]:
random = np.random.rand(7)

In [10]:
random

array([0.70775065, 0.77844466, 0.71436554, 0.78225655, 0.40185372,
       0.67808805, 0.48502625])

Some array methods

In [11]:
size = arr.size

In [12]:
shape = arr.shape

In [13]:
dtype = arr.dtype

In [16]:
dtype

dtype('int64')

Operations with the arrays

In [18]:
arr + 1

array([2, 3, 4, 5, 6])

In [22]:
python_list = [0,1,2,3,4]
[elem + 1 for elem in python_list]

[1, 2, 3, 4, 5]

In [19]:
arr - 1

array([0, 1, 2, 3, 4])

In [20]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [25]:
python_list * 2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [26]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [27]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [28]:
arr % 2

array([1, 0, 1, 0, 1])

In [29]:
arr > 2

array([False, False,  True,  True,  True])

In [30]:
arr[arr > 2]

array([3, 4, 5])

In [31]:
arr[arr % 2 == 0]

array([2, 4])

In [32]:
arr[arr % 2 == 0] = 0

In [33]:
arr

array([1, 0, 3, 0, 5])

In [34]:
arr[0]

1

In [35]:
arr[1:3]

array([0, 3])

In [36]:
arr.sum()

9

In [37]:
arr.mean()

1.8

In [38]:
arr.std()

1.9390719429665317

In [39]:
arr.max()

5

Matrix

In [41]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

Transpose

In [42]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [47]:
transposed = matrix.transpose()

In [48]:
np.dot(matrix, transposed)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

# Matrix determinant

In [51]:
np.linalg.det(matrix)

6.0

In [50]:
matrix = np.array([[1,0,0],[0,2,0],[0,0,3]])

Matrix inverse


In [52]:
np.linalg.inv(matrix)

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

In [53]:
np.dot(matrix, np.linalg.inv(matrix))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

System of linear equations

In [54]:
A = np.array([[2, 1], [1, 1]])
b = np.array([1, 1])

In [55]:
solution = np.linalg.solve(A, b)

In [56]:
solution

array([0., 1.])

In [57]:
np.dot(A, solution)

array([1., 1.])

In [ ]:
# Scalar product of two vectors

In [58]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)

32

In [59]:
a * b

array([ 4, 10, 18])

In [ ]:
# Квадратне рівняння

In [73]:
a = 1
b = 0
c = 1

In [74]:
solution = np.roots([a, b, c])

In [75]:
solution

array([-0.+1.j,  0.-1.j])

In [ ]:
# x*2 - 3x + 2 = 0
# 4 - 6 + 2 = 0
# 1 - 3 + 2 = 0

In [ ]:
# How Python stores floats

In [76]:
a = 0.1
# 1 * 10 ** -1

In [77]:
import math
math.median([1,2,3,4,5])

AttributeError: module 'math' has no attribute 'median'